spring:
  datasource:
    url: ${DB_JDBC_URL}?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

coolsms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_SECRET_KEY}
    senderNumber: ${SENDER_NUMBER}

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-milliseconds: ${JWT_TOKEN_VALIDITY}

cors:
  allowed-origins:
    - ${CORS_ALLOWED_ORIGINS}
