spring:
  datasource:
    url: ${DB_JDBC_URL}?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath*:database/data.sql
      platform: MySQL

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

coolsms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_SECRET_KEY}
    senderNumber: ${SENDER_NUMBER}

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-milliseconds: ${JWT_TOKEN_VALIDITY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enable: true
  cache:
    disabled: true
  use-fqn: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

server: ${PRODUCTION_SERVER_URL}
